-- Create admin_emails table
create table if not exists admin_emails (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add admin email for agrinolan@gmail.com
insert into admin_emails (email)
values ('agrinolan@gmail.com')
where not exists (
  select 1 from admin_emails where email = 'agrinolan@gmail.com'
);

-- Add admin email for tammylouise407@gmail.com
insert into admin_emails (email)
select 'tammylouise407@gmail.com'
where not exists (
  select 1 from admin_emails where email = 'tammylouise407@gmail.com'
);

-- Add RLS policies
alter table admin_emails enable row level security;

-- Admins can view all admin emails
create policy "Admins can view all admin emails"
  on admin_emails for select
  using (
    exists (
      select 1 from admin_emails where email = auth.email()
    )
  );

-- Admins can insert new admin emails
create policy "Admins can add new admin emails"
  on admin_emails for insert
  with check (
    exists (
      select 1 from admin_emails where email = auth.email()
    )
  );

-- Admins can delete admin emails
create policy "Admins can remove admin emails"
  on admin_emails for delete
  using (
    exists (
      select 1 from admin_emails where email = auth.email()
    )
  );
